//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define ID_CHANGE_TEXTURE               2
#define ID_TEXTURE_MANAGER              3
#define ID_CHANGE_WATER_TEXTURE         4
#define IDI_ICON1                       103
#define ICON2                           104
#define IDD_MAIN_BAR                    107
#define IDC_MAIN_STATUS                 108
#define IDB_BITMAP3                     116
#define IDD_POLY_COUNT                  123
#define IDR_MENU1                       124
#define IDD_TEXTURE_MAN                 127
#define IDD_MODEL_MANAGER               128
#define IDR_RT_MANIFEST1                131
#define IDD_TERRAIN_TEXTURE             132
#define IDD_TERRAIN_HEIGHT              133
#define IDD_TERRAIN_PROP                135
#define IDD_SPLASH_SCREEN               136
#define IDD_TERRAIN_VALUES              137
#define IDD_TEX_WINDOW                  138
#define IDD_VIEW_PROP                   139
#define IDD_PROP_PROP                   140
#define IDD_FOLIAGE_PROP                141
#define IDD_WATER_PROP                  142
#define IDD_MAIN_PORT                   143
#define IDD_DIALOG1                     145
#define IDD_WATER_TEXTURE               147
#define IDD_WATER_OPTICAL               148
#define IDD_WATER_MANAGEMENT            149
#define IDD_ATMOSPHERE_PROP             150
#define IDD_ATMOSPHERE_ENV              151
#define IDD_ATMOSPHERE_SKY              152
#define IDD_ATMOSPHERE_MANAGEMENT       153
#define IDD_OCTREE_PROP                 154
#define IDC_COMBO1                      1006
#define IDC_CHECK1                      1007
#define IDC_TERRAIN_TILE_SIZE           1007
#define IDC_CUSTOM1                     1008
#define IDC_EDIT1                       1021
#define IDC_FUCKTHIS                    1021
#define IDC_OCTREE_OBJECTS              1021
#define IDC_EDIT2                       1022
#define IDC_PUBE                        1022
#define IDC_OCTREE_NODE_SIZE            1022
#define IDC_EDIT3                       1023
#define IDC_EDIT4                       1024
#define IDC_EDIT5                       1025
#define IDC_EDIT6                       1026
#define IDC_ANIM_SPEED_X                1026
#define IDC_PROP_POS_Y                  1026
#define IDC_ANIM_SPEED_Y                1027
#define IDC_EDIT7                       1027
#define IDC_PROP_POS_Z                  1027
#define IDC_EDIT8                       1028
#define IDC_PROP_ROT_X                  1028
#define IDC_EDIT9                       1029
#define IDC_PROP_ROT_Y                  1029
#define IDC_EDIT10                      1030
#define IDC_PROP_ROT_Z                  1030
#define IDC_EDIT11                      1031
#define IDC_PROP_SCALE_X                1031
#define IDC_EDIT12                      1032
#define IDC_PROP_SCALE_Y                1032
#define IDC_EDIT13                      1033
#define IDC_PROP_SCALE_Z                1033
#define IDC_BUTTON3                     1048
#define IDC_BUTTON4                     1049
#define IDC_TOGGLE_GRID                 1049
#define IDC_SHADOW_GENERATE             1049
#define IDC_PIVOT_CAM                   1050
#define IDC_RENDER_OCTREE               1050
#define IDC_FREE_CAM                    1051
#define IDC_GRID_PROP                   1052
#define IDC_OPEN_TERRAIN_MENU           1052
#define IDC_TERRAIN_TEXTURE             1053
#define IDC_HOME                        1053
#define IDC_TERRAIN_HEIGHT              1054
#define IDC_BUTTON1                     1054
#define IDC_RECALCULATE_NORMALS         1054
#define IDC_PIVOT                       1054
#define IDC_NEW_MODEL_INSTANCE          1054
#define IDC_OPEN_PROP_MENU              1054
#define IDC_TRANSLATE                   1054
#define IDC_BUTTON2                     1055
#define IDC_POLY_PROGRESS               1055
#define IDC_CLOSE                       1055
#define IDC_FLATTEN_ALL                 1055
#define IDC_FREE                        1055
#define IDC_ROTATE                      1055
#define IDC_OPEN_FOLIAGE_MENU           1055
#define IDC_WATER_SCALE2                1055
#define IDC_TERRAIN_DELETE              1055
#define IDC_OCTREE_TRANSLATE            1055
#define IDC_SKY_TEXTURE_MANAGER         1055
#define IDC_SCALE                       1056
#define IDC_OPEN_WATER_MENU             1056
#define IDC_OCTREE_SCALE                1056
#define IDC_TERRAIN_MIRROR              1056
#define IDC_BUTTON6                     1057
#define IDC_OPEN_ATMOSPHERE_MENU        1057
#define IDC_WATER_ADD                   1057
#define IDC_BUTTON7                     1058
#define IDC_WATER_DELETE                1058
#define IDC_OPEN_OCTREE_MENU            1058
#define IDC_BUTTON8                     1059
#define IDC_SELECT_PROP                 1059
#define IDC_WATER_SELECT                1059
#define IDC_HOME2                       1059
#define IDC_LOAD                        1059
#define IDC_HOME3                       1060
#define IDC_SAVE2                       1060
#define IDC_STATS                       1061
#define IDC_MODEL_FILE                  1061
#define IDC_POLY_NUMBERS                1061
#define IDC_HOME4                       1061
#define IDC_UNDO                        1061
#define IDC_TEXTURE_WINDOW              1062
#define IDC_HOME5                       1062
#define IDC_REDO                        1062
#define IDC_MODEL_WINDOW                1063
#define IDC_HOME6                       1063
#define IDC_SKYBOX_WINDOW               1063
#define IDC_COPY                        1063
#define IDC_SLIDER1                     1064
#define IDC_BLOOM_LUMINANCE             1064
#define IDC_SIZE_SLIDER                 1065
#define IDC_SHADOW_OFFSET               1065
#define IDC_STR_SLIDER                  1066
#define IDC_FADE_SLIDER                 1067
#define IDC_ACTIVE_TEXTURE              1068
#define IDC_ACTIVE_WATER_TEXTURE        1069
#define IDC_TAB_TERRAIN_OPTIONS         1072
#define ID_ADD_TEXTURE                  1073
#define IDC_SCROLLBAR1                  1074
#define IDC_TEXTURE_SCROLLBAR           1074
#define IDC_COMBO_SIZES                 1075
#define IDC_SPIN1                       1077
#define IDC_SPIN2                       1078
#define IDC_ORIGIN                      1079
#define IDC_MODEL_LIST                  1080
#define IDC_ORIGIN2                     1080
#define IDC_SHADOW                      1080
#define ID_CLOSE                        1081
#define ID_ADD_MODEL                    1082
#define IDC_MODEL_NAME                  1083
#define IDC_COMBO_CULLS                 1086
#define IDC_COMBO_WATER_TYPES           1087
#define IDC_COMBO_ANIM_TYPE             1088
#define IDC_REFDIS_X                    1089
#define IDC_REFDIS_Y                    1090
#define IDC_RAFDIS_X                    1091
#define IDC_RAFDIS_Y                    1092
#define IDC_FOLIAGE_MODEL_VIEW          1093
#define IDC_FOLIAGE_SCALE_FROM          1094
#define IDC_FOLIAGE_SCALE_TO            1095
#define IDC_FOLIAGE_ROTATE_FROM         1096
#define IDC_FOLIAGE_ROTATE_TO           1097
#define IDC_FOLIAGE_OFFSET_X            1098
#define IDC_FOLIAGE_OFFSET_Y            1099
#define IDC_FOLIAGE_OFFSET_Z            1100
#define IDC_FOLIAGE_MODEL_LIST          1101
#define IDC_PROP_                       1102
#define IDC_PROP_MODEL_LIST             1102
#define IDC_FOCUS_MODEL                 1103
#define IDC_PROP_MODEL_VIEW             1104
#define IDC_PROP_POS_X                  1105
#define IDC_REMOVE_MODEL                1106
#define IDC_LIST1                       1109
#define IDC_TAB_WATER_OPTIONS           1110
#define IDC_WATER_TRANSLATE             1111
#define IDC_WATER_ROTATE                1112
#define IDC_TERRAIN_ADD                 1113
#define IDC_TAB_ATMOSPHERE_OPTIONS      1114
#define IDC_ATMOSPHERE_ADD              1115
#define IDC_ATMOSPHERE_DELETE           1116
#define IDC_ATMOSPHERE_TRANSLATE        1117
#define IDC_ATMOSPHERE_SCALE            1118
#define IDC_GRID_SIZE                   1119
#define IDC_CELL_SIZE                   1120
#define IDC_TERRAIN_GRID_SIZE           1121
#define IDC_SHADOW_SIZE                 1122
#define IDC_BLOOM_SIZE                  1123
#define IDC_TOGGLE_BLOOM                1125
#define IDC_BLOOM_PASSES                1126
#define IDC_BUILD_OCTREE                1127
#define IDC_VIEW_OCTREE                 1128
#define IDC_SHADOW_POSITION             1129
#define IDC_SHADOW_REAL_TIME            1130
#define IDC_TEXTURE_TYPES               1131
#define IDC_BLOOM_COLOR                 1132
#define IDC_BLOOM_COLOR_B               1133
#define IDC_LIST2                       1134
#define IDC_SKYBOX_VIEWER               1135
#define IDC_CHANGE_BOX                  1136
#define IDC_SCULPT_MODES                1137
#define IDC_LIST3                       1138
#define IDC_TAB1                        1139
#define IDC_TRANSPARENCY_SLIDER         1140
#define IDC_ADD_PROP                    1157
#define IDC_DELETE_PROP                 1158
#define IDC_OPEN_VIEW_MENU              1751
#define IDC_OPEN_MODEL_MANAGER          11054
#define IDC_OPEN_MODEL_MANAGER_P        11059
#define IDC_CUBEMAP_LIST                11348
#define IDC_CUBEMAP_LIST_2              11348
#define ID__FILE                        40001
#define TOOLBARMAIN                     -25535
#define ID__QUIT                        40002
#define ID_ABOUT_ABOUTORGANGRINDER      40003
#define ID_BUTTON40006                  40006
#define IDC_MENU                        40007
#define ID_FILE_COLORCHOOSER            40008
#define ID_FILE_DIALOGUEBOX             40009
#define ID_FILE_IMPORT                  40010
#define ID_IMPORT_CAL3DANIMATEDMESH     40012
#define ID_IMPORT_3DS                   40013
#define ID_COMPILE_SHADER               40014
#define ID_TOOLS_SHADERCOMPILER         40014
#define ID_TERRAIN_MENU                 40015
#define ID_1_2                          40015
#define ID_1_3                          40016
#define ID_1_4                          40017
#define ID_1_5                          40018
#define ID_TOOLS_TEXTUREMANAGER         40019
#define ID_EDIT_UNDO40022               40022
#define ID_EDIT_REDO40023               40023
#define ID_EDIT_COP                     40024
#define ID_EDIT_COPY40025               40025
#define ID_EDIT_PASTER                  40026
#define ID_EDIT_PAST                    40027
#define ID_MODEL_MANAGER                40030
#define ID_TOOLS_POLYGONCOUNTER         40031
#define ID_FILE_EXPORT                  40032
#define ID_EXPORT_TANKYPANKYMAP         40033
#define ID_EXPORT_MODELMANAGERLIBRARY   40035
#define ID_EXPORT_TEXTUREMANAGERLIBRARY 40036
#define ID_FILE_IMPORT40037             40037
#define ID_IMPORT_TEXTUREMANAGERLIBRARY 40038
#define ID_IMPORT_MODELMANAGERLIBRARY   40039
#define ID_IMPORT_TANKYPANKYMAP         40040
#define ID_FILE_SAVEFILE                40041
#define ID_FILE_LOADFILE                40042
#define ID_FILE_NEW40043                40043
#define IDD_EXPORT_SF_MAP               40044

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         40045
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
